# Generated by Django 5.1.1 on 2024-09-22 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_rename_group_groupmodel_rename_student_studentmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='groupmodel',
            table='group',
        ),
        migrations.AlterModelTable(
            name='studentmodel',
            table='student',
        ),
    ]
