# Generated by Django 5.1.1 on 2024-09-22 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0005_subjectmodel_exammodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PersonModel",
        ),
    ]
