# Generated by Django 5.1.1 on 2024-09-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_delete_personmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammodel',
            name='type',
            field=models.CharField(choices=[('Partial', 'Partial'), ('Final', 'Final')], default='Partial', max_length=200),
        ),
    ]
