# Generated by Django 5.1.1 on 2024-09-25 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0007_exammodel_type"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="exammodel",
            table="exam",
        ),
    ]
