# Generated by Django 5.1.1 on 2024-10-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0016_myview"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW students_average_score AS
            select s.name as student_name, g.name as group_name, AVG(e.score) as average_score FROM
            exam e inner join student s on e.student_id = s.id 
            inner join "group" g on s.group_id = g.id
            group by s.name, g.name 
            order by average_score DESC
            """,
            reverse_sql="DROP VIEW students_average_score;"
        )
    ]
